---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Alueellisesta ja ammatillisesta kohtaannosta

Arvioin työmarkkinoiden alueellisen ja ammatillisen kohtaannon kehitystä Suomessa vuodesta 2006 alkaen. Muodostan kohtaanto-ongelman suuruutta mittaavan indeksin \cite{csahin2014mismatch}, joka kuvaa kuinka epätasapainoisesti työttömät työnhakijat ja avoimet työpaikat ovat sijoittuneet eri alueille ja eri ammatteihin verrattuna tilanteeseen, jossa alueellinen tai ammatillinen liikkuvuus eivät olisi rajoitteita. Arvioin sekä alueellisen että ammatillisen kohtaanto-ongelman trendinomaisesti pienentyneen 2000-luvun aikana. Kokonaisuudessaan työmarkkinoiden kohtaanto on Beveridge-käyrällä mitattuna kuitenkin heikentynyt. Koska epätasapaino työttömien työnhakijoiden ja avoimien työpaikkojen alueellisessa ja ammatillisessa jakaumassa on pienentynyt kohtaannon heikentyminen tuskin johtuu alueellisen tai ammatillisen liikkuvuuden kehityksestä tai rajoitteista.

## Installation

You can install the development version of kohtaantoindeksit from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("pttry/kohtaantoindeksit")
```
